### ISSUE TITLE
make_DESeq_heatmap.R

### ISSUE THREAD

**Issue by seb951** [transcript/samsa2#10]
It's not entirely clear how the clustering is done in this script to generate the heatmap, but the same (sample) clustering seems to applied to both the x and y axis. Therefore, the information in the heatmap is actually only one dimensional and redundant.

Instead, in gene expression studies, data is usually clustered by samples on one axis, while on the other, genes are clustered. Also, to avoid having thousands of genes (or here: organisms, functions or subsystems) on heatmap, usually only the expression of differentially expressed genes are used for clustering (see for example pheatmap(test) in ?pheatmap). Updates to script should reflect that I think. Thanks.

**Comment by transcript** [comment]
This is a good point.

I've reworked the "make_DESeq_heatmap.R" script to reflect this - the script now compares organism (or function, or functional category) to sample.  The number of represented categories is currently manually thresholded (set from command line with -N flag), although I'm looking into making it default to automatically pick the number of differentially expressed organisms/functions/categories.

I'm closing this, as the update is pushed (although not yet added to latest release - that will come after a few more updates are incorporated).
