### ISSUE TITLE
snakemake implementation of samsa2 pipeline

### ISSUE THREAD

**Issue by wresch** [transcript/samsa2#11]
Hi,

i started working on a snakemake implementation of the samsa2 pipeline that can 

- use single ended and paired end sample
- progressively add more samples to the same experiment without re-running unnecessary
  computation
- run tasks as cluster jobs in parallel

would you guys be interested in incorporating that into samsa2?  It's not quite done yet but getting close.

Regards,
Wolfgang

**Comment by transcript** [comment]
Hi Wolfgang,

Yes, this could be very useful!  Please keep me updated and let me know if you need assistance.  As a note, I'm incorporating changes from user Kaedenn to better conform to some software development tenets, so there may be an updated SAMSA2 master in the next couple days.

Best,
Sam

**Comment by transcript** [comment]
Hi Wolfgang, 

I've pushed an update that better handles some of the pathing for the master script, so I'd pull the most recent version if you're pursuing this.

Best,
Sam

**Comment by wresch** [comment]
Ok. Thanks. Still working on it. Once I have it working I'll do a pull
request
