### ISSUE TITLE
IndexElist index out of rangerror:

### ISSUE THREAD

**Issue by sghignone** [transcript/samsa2#29]
I am trying to work with the full release of RefSeq, so following instruction I have downloaded and concatenated all the files, and produced the DIAMOND index, using the gzipped file. In order to save disk space I have left the gzipped RefSeq full file in the database folder, but it ended up it's not a good move..In fact, when running the master-script, at DIAMOND_analysis_counter.py step, I get:

>Starting database analysis now.
Traceback (most recent call last):
  File "/home/stefano/scripts/samsa2/python_scripts/DIAMOND_analysis_counter.py", line 138, in <module>
    db_entry = db_entry[1][:-1]
IndexError: list index out of range
'python /home/stefano/scripts/samsa2/python_scripts/DIAMOND_analysis_counter.py -I /home/stefano/GoogleDrive/TEST-SAMSA2/step_4_output/MO1.R1.anqrpht.clean.fastq.merged.RefSeq_annotated -D /home/stefano/scripts/samsa2/full_databases/RefSeq_full.gz -O' exited with non-zero status 1

I suppose the error arise since the DIAMOND_analysis_counter.py does not check and process gzipped files: indeed, I uncompressed the file, and the script worked fine. 

So maybe it could be useful do add the capability of handling gzipepd file to DIAMOND_analysis_counter.py (and other scripts, using that db)
Cheers,
Stefano

**Comment by transcript** [comment]
Hi Stefano, you are completely correct that the Python scripts don't work with a gzipped database currently.  I've tagged this as a future enhancement, and will look into this when I get a chance.

Thanks!
