### ISSUE TITLE
Showing error in diamond subsystem analysis

### ISSUE THREAD

**Issue by amit19bik** [transcript/samsa2#30]
After running the pipeline in diamond subsystem analysis step i am getting some error.
Kindly help me to solve the error. The error message is listed below.

Traceback (most recent call last):
  File "python_scripts/DIAMOND_subsystems_analysis_counter.py", line 119, in <module>
    for line in db:
  File "/home/amit/anaconda3/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 3173: invalid start byte

Thank you.
Kind regards,
Amit

**Comment by transcript** [comment]
Resolved!  Looks like there's some character in the Subsystems database that doesn't match UTF-8 encoding.  The Subsystems Python parser script will now ignore that character and will run properly with Python3.7.

Amit, you will need to re-pull the DIAMOND_subsystems_analysis_counter.py file from in the python_scripts directory.

**Comment by amit19bik** [comment]
Thank you so much Sam.
