### ISSUE TITLE
Errors in master_script_preserving_unmerged.sh and combining_unmerged.R

### ISSUE THREAD

**Issue by callumjethomas** [transcript/samsa2#31]
Hi, I am getting errors when trying to run the master script for including unmerged reads ("master_script_preserving_unmerged.sh"). The errors seem to stem from lines 159-161 of the script.

> $R_programs/combining_umerged.R $STEP_1
> 
> printf "MERGING\n" >>pipeline/checkpoints

This gives the errors:

> line 178: /combining_umerged.R: No such file or directory
> insect_script.sh: line 180: pipeline/checkpoints: No such file or directory

I tried replacing the unfound variables **$R_programs** with $R_DIR and **pipeline/checkpoints** with $INPUT_DIR/checkpoints.

However then I get an error related to the R script "combining_unmerged.R"

> /cvmfs/soft.computecanada.ca/easybuild/software/2017/avx2/Compiler/intel2016.4/r/3.5.0/bin/Rscript: bad interpreter: No such file or directory

Any help with this would be appreciated. Thanks!

**Comment by transcript** [comment]
Hi Callum,

Thanks for catching the bad variables!  I've updated that bash script to contain the proper variables, and I've also added an explicit Rscript call for that line.  Can you try pulling this latest version of the bash script and see if it now runs?

Thanks,
Sam

**Comment by callumjethomas** [comment]
Hi Sam,

Thanks for the response. I've tried running the updated script and now I get the following errors:

```
ls: cannot access '*unassembled.forward.fastq': No such file or directory
ls: cannot access '*unassembled.reverse.fastq': No such file or directory
ls: cannot access '*.assembled.fastq': No such file or directory
Error in read.table("umerged.forward.files", stringsAsFactors = F) : 
  no lines available in input
```

I presume these are related to the R script being unable to find the right files in the $OUTPUT_DIR?

Also there is another bad variable in the "TRIMMO" section of the master script

`printf "TRIMMO\n" >>pipeline/checkpoints`

instead of

`printf "TRIMMO\n" >> $INPUT_DIR/checkpoints`

**Comment by transcript** [comment]
Hi Callum,

Thanks for catching the other checkpoint bug; I've updated the script.

I'm not sure why you're seeing the other error, however - can you take a look at the files that are in the step_1_output/ folder in the output directory you specified, and give me a list of those?  I'm not sure if the R script isn't finding files that are properly there, or if the files themselves are missing.

Thanks,
Sam

**Comment by callumjethomas** [comment]
Hi Sam,

The files in question are actually in the folder "step_2_output".

```
step_1_output:
TOG-EHJP-1177-1-1_S1_L001.cleaned.forward
TOG-EHJP-1177-1-1_S1_L001.cleaned.forward_unpaired
TOG-EHJP-1177-1-1_S1_L001.cleaned.reverse
TOG-EHJP-1177-1-1_S1_L001.cleaned.reverse_unpaired

step_2_output:
TOG-EHJP-1177-1-1_S1_L001.merged.assembled.fastq
TOG-EHJP-1177-1-1_S1_L001.merged.discarded.fastq
TOG-EHJP-1177-1-1_S1_L001.merged.unassembled.forward.fastq
TOG-EHJP-1177-1-1_S1_L001.merged.unassembled.reverse.fastq 
```

**Comment by callumjethomas** [comment]
I worked it out.

The bash script is telling R to look for the files in the $STEP_1 directory. So the code should read:

> Rscript $R_DIR/combining_unmerged.R **$STEP_2**

> printf "MERGING\n" >> $INPUT_DIR/checkpoints
> **~~mv $STEP_1/*assembled2.fastq $STEP_2/~~**

After fixing this the code runs without errors. Thanks for your help, and for writing the script!

**Comment by transcript** [comment]
Great!  Script updated, thank you Callum!
