### ISSUE TITLE
Fail to install R 3.0 Ubuntu 16.04LTS

### ISSUE THREAD

**Issue by wxp16** [transcript/samsa2#32]
Hello 

Before running  the `package_installation.bash`,  I tried to install `R 3.0.2` on the `Ubutu16.04LTS ` from the source code, but failed. Here is link of installing R3.0.2 https://stackoverflow.com/questions/39870825/installing-r-3-0-2-in-ubuntu-16-04
Our Linux was installed in `VirtualBox` on Windows10

I wanted to ask what Linux OS and R version  did you use? 

We also used the following command to install R3.5. but couldn't install the R packages
```
sudo apt install r-base-core
```
Please advise..
Thanks

**Comment by transcript** [comment]
Hello,

I've run this on Ubuntu 16.04, using R version 3.4.3 (Kite-Eating Tree).  You could try this version of R.

I've also run the pipeline successfully using R 3.2.3, which can be installed using the following commands on Ubuntu 16.04:

```
wget https://cran.r-project.org/src/base/R-3/R-3.2.3.tar.gz
sudo apt-get install libxt-dev --yes
sudo apt-get install default-jre --yes
tar xvf R-3.2.3.tar.gz
cd R-3.2.3/
./configure
make
```

For installing the R packages, from the samsa2/ home directory, you can run

`bash setup_and_test/package_installation.bash`

Best,
Sam

**Comment by wxp16** [comment]
Thank you Sam. I have installed R 3.4 and the R packages. The test run went well.
