### ISSUE TITLE
problems running "test_of_master_script_tiny.bash"

### ISSUE THREAD

**Issue by tony-travis** [transcript/samsa2#33]
Hi,
We had problems running "test_of_master_script_tiny.bash" under Ubuntu-MATE 18.04 because of the way BASH_SOURCE is used to get the directory where the script is running from and where the scripts are in the ../bash_scripts below it - The BASH_SOURCE strategy only works if an absolute path is used to invoke the test e.g.:

  bash /home/username/samsa2/setup_and_test/test_of_master_script_tiny.bash

There are also a couple of bugs in "bash_scripts/lib/common.h":
#1 $SAMSA prefix is missing for the awk source file
#2 Command not found error because $@ is quoted inappropriately

```
diff --git a/bash_scripts/lib/common.sh b/bash_scripts/lib/common.sh
index b8cf7ed..141c0ca 100644
--- a/bash_scripts/lib/common.sh
+++ b/bash_scripts/lib/common.sh
@@ -42,7 +42,7 @@ export LOGFILE
 
 # get_config <varname>
 get_config() {
-  PROG="bash_scripts/lib/parse_config.awk"
+  PROG="$SAMSA/bash_scripts/lib/parse_config.awk"
   VAR_NAME="$1"
   DEF_VAL="undef"
   for arg in "$@"; do
@@ -97,7 +97,7 @@ fatal() {
 
 # log <cmd...>
 log() {
-  "$@" 2>&1 | tee -a "$LOGFILE"
+  $@ 2>&1 | tee -a "$LOGFILE"
   return ${PIPESTATUS[0]}
 }
```

**Comment by transcript** [comment]
Hi Tony, 

Thank you for raising these issues.  Regarding point 1, I've noted the absolute path issue and am working on a solution.

For point 2, you may want to pull the latest version of SAMSA2 - the awk source file is no longer used, and I believe that the misquote has been resolved in common.sh.

If you pull the latest version and still see these issues, let me know, or please feel free to submit a pull request if you'd like.

Best,
Sam
