### ISSUE TITLE
error with DIAMOND_subsystems_analysis_counter.py

### ISSUE THREAD

**Issue by sudeep71** [transcript/samsa2#35]
Hi,

I get an error with DIAMOND_subsystems_analysis_counter.py when i run the test_of_master_script_tiny.bash

Traceback (most recent call last):
  File "path_to_folder/samsa2/python_scripts/DIAMOND_subsystems_analysis_counter.py", line 105, in <module>
    db = open (db_name, "r", encoding='utf-8', errors='ignore')
TypeError: file() takes at most 3 arguments (4 given)

I have python 2.7.X installed

Thanks

**Comment by transcript** [comment]
Hello,

Thanks for including the Python version - that's what's going wrong here, as Python 2 doesn't allow for specifying the encoding of the file.

I added a try/catch statement that should work around this; try pulling the most recent version of DIAMOND_subsystems_analysis_counter.py from https://github.com/transcript/samsa2/blob/master/python_scripts/DIAMOND_subsystems_analysis_counter.py and see if this fixes the error.  (Also, please let me know if you then run into a UTF-8 encoding error later on, as I'll have to build additional methods to handle any special characters in the database if using Python2.)

Best,
Sam
