### ISSUE TITLE
Help with scripts

### ISSUE THREAD

**Issue by mradz19** [transcript/samsa2#38]
I'm new to running bash scripts so I was hoping to get some advice...

I downloaded samsa2 and have tried following the guidelines for installation using the scripts in the setup_and_test folder.

I have used gmod +x to give executable permission to the scripts and I try to run them using:

bash pathway_to_script.sh

When doing this I get the following error:

package_installation.bash: line 32: package_installation.bash/../bash_scripts/lib/common.sh: Not a directory

When looking at the script I see this line:

# Set pathway for SAMSA to location of samsa2 GitHub download:
IGNORE_DEPS=1 source "${BASH_SOURCE%/*}/../bash_scripts/lib/common.sh"

What is the correct way to set this pathway? Do I need to delete the whole line as it is and add in the path to the samsa2 download or is there another way to do it?

Thanks for your help!

**Comment by transcript** [comment]
Simple fix - run the command as follows (note the slash for location):

`bash ./package_installation.bash`

Longer fix - it looks like if the path (including current directory) isn't provided, this line throws an error.  I'll see if I can write an error handling fix for this and update the repo.

**Comment by transcript** [comment]
Added an error handler in commit #63519f45c05ac22c7b19b19d77890a50f1312a7a.

**Comment by bart1920** [comment]
Hi I'm new to bash and I have a similar issue - I am not able to set the location for SAMSA to the location of samsa2 GitHub download. 
I entered this command line: source "${BASH_SOURCE%/*}/../bash_scripts/lib/common.sh" and filled in the location where SAMSA should go: $ source "${BASH_SOURCE%/*}/C:/Users/username/samsa2/bash_scripts/lib/common.sh". However, shell returns 'no such file or directory'. What should I do to make this work?
