### ISSUE TITLE
High number of hypothetical proteins

### ISSUE THREAD

**Issue by mradz19** [transcript/samsa2#40]
I've been interested in looking at genes associated with a particular genus (Streptococcus), to do this I have run the DIAMOND_specific_organism_retriever.py script followed by DIAMOND_analysis_counter.py. When pulling out reads using the first script I am able to get roughly 10k to 100k reads depending on sample. However when running the analysis counter roughly 70-90% of the reads are annotated as "hypothetical proteins".

Is that to be expected and is there any way to improve on this? I find the results quite surprising considering how well studied Strep is.

**Comment by transcript** [comment]
Hey Michael,

Short answer: this is based on the RefSeq database that's used, and there's not a great way to improve the database itself.

Longer answer, with a potential avenue forward: there's no reason, however, to just stick to one database, especially if you're isolating out Streptococcus!  One approach could be to do the following:

1. Run the DIAMOND_specific_organism_retriever.py on your general results to isolate out the Streptococcus-specific reads.
2. Retrieve the raw reads in FASTQ format.  I don't have a tool for this, but it would be fairly straightforward to loop through the Streptococcus-specific reads and get a list of all read IDs, and then loop through the original FASTQ file and, if a read ID matches the Streptococcus list, print it to an output.
3. Take this new FASTQ of Streptococcus-specific reads and use DIAMOND to align them against a list of all Streptococcus proteins, which may be better annotated than the RefSeq overall reference (you'd want to check this to be certain, maybe look at how many total proteins are in the file versus the number of "hypothetical protein" occurrences).

This could help improve the annotation percentage.  Let me know if this approach doesn't make sense, or if you have another suggestion, and I'm happy to help!

(Another option could be to find/create a Streptococcus-specific reference database in the fashion described above, turn that into a DIAMOND database, and then use DIAMOND to search your entire original reads file against that.  This saves you having to do the organism-specific filtering step - although you'd probably want some sort of comparison or sanity check to make sure that hits to the Streptococcus-specific database are not just homologs from other bacteria.)
