### ISSUE TITLE
'Bacteria' in the result of combined_graphs_unified.R	

### ISSUE THREAD

**Issue by Shicheng-Guo** [transcript/samsa2#45]
Hi Sam, 

Applying combined_graphs_unified.R and SAMSA2 pipeline, I obtained a figure as the blow. My question is how to understand the 'Bacteria' in the Genus list since I think all others also belong to `bacteria`, right? Hope to receive some explanation to my confusion. Thanks. 

Shicheng

![SAMSA2-2020-Shicheng-Guo-Strain-Skin](https://user-images.githubusercontent.com/6641283/74692181-9a683700-51ab-11ea-9b84-942257e554e3.JPG)

**Comment by transcript** [comment]
Hi Shicheng,

You're correct - the Bacteria entry is for annotations that are not specific beyond the Bacteria kingdom.  There are some entries in the RefSeq database that are just labeled as "bacterial spp.", without any more detailed taxonomic information.  These ones are classified here as this Bacteria top-level category.

**Comment by Shicheng-Guo** [comment]
Dear Sam, 

So here should I take the value as 'overall bacteria' reads or "unclassified bacteria" reads? 

Thanks. 

Shicheng

**Comment by transcript** [comment]
Hi @Shicheng-Guo,

This would be "unclassified bacteria" reads.

Best,
Sam
