### ISSUE TITLE
Error with DIAMOND Database

### ISSUE THREAD

**Issue by mweberr** [transcript/samsa2#48]
The master script stops after the ribo-depletion step  with error

> Error: Database file is not a DIAMOND database.

`'diamond blastx --db samsa2/full_databases/RefSeq_bac -q samsa2/step_3_output/test.merged.ribodepleted.fastq -a test.merged.ribodepleted.fastq.RefSeq -t ./ -k 1' exited with non-zero status 1`

Do I have to convert the RefSeq_bac to DIAMOND format ?

Thanks for you help!

**Comment by transcript** [comment]
Hi there,

Yes, you've got the nail on the head - the RefSeq_bac database will need to be in DIAMOND-compressed format.

You can do this by running:

`diamond makedb --in RefSeq_bac -d RefSeq_bac_dmnd`

Be sure to supply the DIAMOND-compressed database for step 4, but use the regular (plain-text) database for step 5, when you get the nice summary of results.

Best,
Sam
