### ISSUE TITLE
Checkpoint TRIMMO

### ISSUE THREAD

**Issue by mweberr** [transcript/samsa2#56]
Hi,

the first step of TRIMMING is repeated, probably because the checkpoint is not written.

the first checkpoint trimming is created at line 125 master_script.sh
`printf "TRIMMO\n" >>pipeline/checkpoints`

All other checkpoints are written into 
`printf` "MERGING\n" >>$INPUT_DIR/checkpoints

Can you please explain shortly what the checkpoint is doing with the debug function ?
# checked <cmd...>
```
checked() {
  if [[ -n "$DRY_RUN" ]]; then
    debug "DRY RUN: $@"
    logstr "$@"
  else
    debug "Running $@"
    log "$@"
    status=$?
    if [[ $status -ne 0 ]]; then
      echo "'$@' exited with non-zero status $status" >&2
      exit $status
    fi
    debug "Finished running $@"
  fi
}
```

**Comment by transcript** [comment]
Hello, thanks for the catch on the TRIMMING not being properly written to the log file!  I've corrected this.

For the debugging `DRY RUN` function, this prints a lot more content out to the log, including the date and time that different components start, which component is running at a time, and also whether any step fails.  

I've submitted PR #56 to correct for the trimmomatic step.
