### ISSUE TITLE
Error in R-analysis step

### ISSUE THREAD

**Issue by dhananyashunmugam** [transcript/samsa2#76]
I'm running samsa2 with the sample data given. I had R-packages issue, so i have installed them separately and tried to run this last command given below here. Its showing the following error. 

`Rscript /mnt/h/Programs/samsa2/R_scripts/Subsystems_DESeq_stats.R -I /mnt/h/Programs/samsa2/sample_files_paired-end/1_starting_files/step_5_output/Subsystems_results/ -O Subsystems_level-1_DESeq_results.tab -L 1 -R /mnt/h/Programs/samsa2/sample_files_paired-end/1_starting_files/step_2_output/raw_counts.txt`

Error: 
```
[1] "USAGE: $ Subsystems_DESeq_stats.R -I input_directory/ -O save.filename -L level (1,2,3,4) [-R raw_counts_file]"
Working directory is  /mnt/h/Programs/samsa2/sample_files_paired-end/1_starting_files/step_5_output/Subsystems_results/
Saving results as  Subsystems_level-1_DESeq_results.tab
Calculating DESeq results for hierarchy level  1
Now importing raw counts, if provided.
Now running DESeq.
converting counts to integer mode
estimating size factors
estimating dispersions
gene-wise dispersion estimates
mean-dispersion relationship
-- note: fitType='parametric', but the dispersion trend was not well captured by the
   function: y = a/x + b, and a local regression fit was automatically substituted.
   specify fitType='local' or 'mean' to avoid this message next time.
Error in lfproc(x, y, weights = weights, cens = cens, base = base, geth = geth,  :
  newsplit: out of vertex space
Calls: DESeq ... estimateDispersionsFit -> localDispersionFit -> locfit -> lfproc
In addition: There were 17 warnings (use warnings() to see them)
Execution halted
```

**Comment by RJ3** [comment]
Having this issue now, what was the solution?
Using R 3.6.1

**Comment by transcript** [comment]
I know this comment was a while ago (trying to address old comments in the new year), but a couple useful threads:

https://support.bioconductor.org/p/97424/

https://support.bioconductor.org/p/84696/

This can sometimes occur if the raw_counts list of samples doesn't match the number of input files you're trying to annotate, like if you added or removed some samples after the raw_counts.txt was generated.
