### ISSUE TITLE
test_of_master_script.py

### ISSUE THREAD

**Issue by spencerlong1** [transcript/samsa2#78]
Hi,

I am just starting with setting up DRAM for the first time, and finding issues with the master script test.

this is the message I get when I run it

(samsa2) [sdl1u18@cyan52 samsa2]$ bash setup_and_test/test_of_master_script_tiny.bash 
WARNING: THIS IS A TEST RUN.
You are running an example script to test SAMSA2 using TINY databases.
To run real metatranscriptomes, please download one or both of the databases by running full_database_download.bash located at https://github.com/transcript/samsa2/tree/master/setup.
NOTE: Before running this script, please download and run package_installation.bash located at https://github.com/transcript/samsa2/tree/master/setup in order to set up SAMSA2 dependencies.

Using SAMSA at /mainfs/home/sdl1u18/samsa2
setup_and_test/../bash_scripts/lib/common.sh: line 53: java: command not found

I am wondering what this may be- Do I need to install java on my cloud computing environment, and if so what version? I cant spot in common.sh what the exact issue is.

thanks,
Spencer

**Comment by spencerlong1** [comment]
Seem to have solved this myself, installed openjdk (latest release) and now it is running

**Comment by transcript** [comment]
Glad to hear!  I'll mark this as closed but leave it archived for others who encounter this issue.
