### ISSUE TITLE
make_combined_graphs.R

### ISSUE THREAD

**Issue by seb951** [transcript/samsa2#8]
currently, Lines 30-33 read:
} else {
  cat ("Working directory is ", opt$directory, "\n")
  wd_location <- opt$directory
}

it is missing the setwd() step (as in other scripts) and should read:
} else {
  cat ("Working directory is ", opt$directory, "\n")
  wd_location <- opt$directory
  setwd(wd_location)
}

**Comment by transcript** [comment]
Updated and fixed, thank you!
