### ISSUE TITLE
Loosing too many reads after Pear step

### ISSUE THREAD

**Issue by abithapr** [transcript/samsa2#85]
I am loosing too many reads as unassembled forward and reverse reads after running the pear step.

**Comment by transcript** [comment]
Hello,

You could adjust the PEAR parameters for read merging, or you can always combine the forward unmerged reads with your merged result and then proceed.

The easiest approach would probably be to adjust the p-value for PEAR.

PEAR's configuration options are here: https://cme.h-its.org/exelixis/web/software/pear/doc.html#cl-optional

Keep in mind that, as you include more reads, you may get off-target alignments later on.  So it's best to strike a balance between inclusivity and stringency.
