### ISSUE TITLE
Code problems

### ISSUE THREAD

**Issue by iquasere** [transcript/samsa2#9]
Greetings!

I was trying to use SAMSA2, and running the master_script.bash, it fails at line 89 because of what i think is a typo: the "##*/" in "out_name=`echo ${out_path##*/}`". I tried editing that out and further problems arose because of file names (changed *.merged* to *merged.* and *.cleaned to *_cleaned). This edits allowed me to get to the python scripts, however, after identifying the genes, it fails to find their identifiers in the databases for retrieving functional and taxonomic information.

I downloaded SAMSA2 from github, and installed everything with the supplied scripts from the tool. Am I using an older non-functional version of the tool?

Thank you for your attention

**Comment by transcript** [comment]
Hello,

The purpose of the bash expression `echo ${out_path##*/}` is to cut out all preceding path elements.

If the file_path here is `1_starting_files/control_1_TINY.merged`, for example, this bash expression will return `control_1_TINY.merged`.

I'm not sure why you're having issues identifying the functional and taxonomic information of the genes.  Is this a failure in the master script?  Is this occurring on Step 5, when generating the functional results from the RefSeq database?  Are you using the default database (RefSeq_bac)?

Hopefully I can help you fix these issues.

**Comment by transcript** [comment]
I am making some updates to the tool, but this shouldn't be causing issues such as these you're reporting.

**Comment by utpalh** [comment]
I run the program, and got the following problem, 

Calculating DESeq results for hierarchy level  1 
Error in `row.names<-.data.frame`(`*tmp*`, value = value) : 
  duplicate 'row.names' are not allowed
Calls: rownames<- ... rownames<- -> row.names<- -> row.names<-.data.frame
In addition: Warning message:
non-unique values when setting 'row.names': ‘’, ‘1,2-dihydroxy-3-keto-5-methylthiopentene dioxygenase (EC 1.13.11.54)’, ‘1,2-dihydroxycyclohexa-3,5-diene-1-carboxylate dehydrogenase (EC 1.3.1.25)’, ‘1,2-dihydroxynaphthalene dioxygenase’, ‘12-oxophytodienoate reductase (OPR3)(DDE1)’, ‘1,4-alpha-glucan branching enzyme (EC 2.4.1.18)’, ‘1,4-alpha-glucan (glycogen) branching enzyme, GH-13-type (EC 2.4.1.18)’, ‘1,4-dihydroxy-2-naphthoate octaprenyltransferase (EC 2.5.1.74)’, ‘16 kDa heat shock protein A’, ‘16 kDa heat shock protein B’, ‘16S rRNA m(5)C 967 methyltransferase (EC 2.1.1.-)’, ‘16S rRNA processing protein RimM’, ‘1-acyl-sn-glycerol-3-phosphate acyltransferase (EC 2.3.1.51)’, ‘1-deoxy-D-xylulose 5-phosphate reductoisomerase (EC 1.1.1.267)’, ‘1-deoxy-D-xylulose 5-phosphate synthase (EC 2.2.1.7)’, ‘1-hydroxy-2-methyl-2-(E)-butenyl 4-diphosphate synthase (EC 1.17.7.1)’, ‘1-phosphofructokinase (EC 2.7.1.56)’, ‘1-pyr [... truncated] 
Execution halted
 can you let me know how to sort the problem

**Comment by transcript** [comment]
Hi utpalh,

Did this error happen while running the master_script.sh?  Or were you running one of the R scripts separately?

Just from the error that you've pasted in, it looks like you're trying to run the Subsystems_DESeq_stats.R script, but it's having issues with the raw counts table.  Could you upload the raw counts table that you received to this issue?  This should be located in your Step 2 folder.

**Comment by utpalh** [comment]
raw counts 
control_1_Healthy 	21092913
control_2_Healthy 	20298464
control_3_Healthy 	20078549
experimental_4_HLB	19632654
experimental_5_HLB	20712965
experimental_6_HLB	22204048

I run DESeq for REfseq, no problem but for the subsystems_results i have the error

I have run the master_script.sh,  the error came while running the following lines in it. 
Rscript $R_programs/Subsystems_DESeq_stats.R -I $starting_location/step_5_output/Subsystems_results/receipts/ -O Subsystems_level-1_DESeq_results.tab -L 1 -R $starting_location/step_2_output/raw_counts.txt

I tried both the file location with subsystem result files. 
   1)   step_5_output/Subsystems_results/
   2)  step_5_output/Subsystems_results/receipts/

Output

[1] "USAGE: $ run_DESeq_stats.R -I working_directory/ -O save.filename -L level (1,2,3,4)"
Working directory is  /home/utpal/Documents/samsa2/step_5_output/Subsystems_results/receipts/ 
Saving results as  Subsystems_level-1_DESeq_results.tab 
Calculating DESeq results for hierarchy level  1 
Error in `row.names<-.data.frame`(`*tmp*`, value = value) : 
  duplicate 'row.names' are not allowed
Calls: rownames<- ... rownames<- -> row.names<- -> row.names<-.data.frame
In addition: Warning message:

**Comment by transcript** [comment]
Hmm, the counts file contents you posted look fine.  So that's not the issue.

You shouldn't be using the receipts location; this should be calling the files in ```$STEP_5/Subsystems_results```.  Is there a chance you could attach a couple of the results files to this issue?

(You can attach files to a Github comment by dragging them into the text box or using the link at the bottom to select them.)

If you cannot do this, I can try making some more explicit merge commands in the R script and uploading that for you to try in place of yours, but I'm not sure why it's encountering this issue.  I am not seeing this in my tests.

**Comment by utpalh** [comment]
I uploaded 4 files, Check if there is anything you find that are not correct
[4 files.zip](https://github.com/transcript/samsa2/files/2228982/4.files.zip)

**Comment by transcript** [comment]
Ah, that's resolved it!

It looks like the R script was properly converting blank hierarchy entries into "NO HIERARCHY", but was missing when an entry is instead classified as "N/A".  One line fix, and the script now runs without any problems.

I've pushed an update, but I'm also attaching the R script here.  If you replace your "Subsystems_DESeq_stats.R" file with this one, things should work.  (You'll have to gunzip the file, because Github won't let me share a script file directly, but will if it's gzipped.  Go figure.)

[Subsystems_DESeq_stats.R.gz](https://github.com/transcript/samsa2/files/2225453/Subsystems_DESeq_stats.R.gz)

**Comment by utpalh** [comment]
Thanks Sam its working fine now

**Comment by utpalh** [comment]
I came upon the following error while processing for Level 2 subsystem and level 4 subsystem

[1] "USAGE: $ run_DESeq_stats.R -I working_directory/ -O save.filename -L level (1,2,3,4)"
Working directory is  /home/utpal/Documents/samsa2/step_5_output/Subsystems_results/ 
Saving results as  Subsystems_level-2_DESeq_results.tab 
Calculating DESeq results for hierarchy level  2 
Error in setnames(x, value) : 
  Can't assign 4 names to a 3 column data.table
Calls: colnames<- ... colnames<- -> names<- -> names<-.data.table -> setnames
Execution halted
[1] "USAGE: $ run_DESeq_stats.R -I working_directory/ -O save.filename -L level (1,2,3,4)"
Working directory is  /home/utpal/Documents/samsa2/step_5_output/Subsystems_results/ 
Saving results as  Subsystems_level-1_DESeq_results.tab 
Calculating DESeq results for hierarchy level  4 
Error in `row.names<-.data.frame`(`*tmp*`, value = value) : 
  duplicate 'row.names' are not allowed
Calls: rownames<- ... rownames<- -> row.names<- -> row.names<-.data.frame
In addition: Warning message:
non-unique value when setting 'row.names': ‘NO HIERARCHY’ 
Execution halted
